// UX-pass demo fixtures (small level): 11 fictional businesses, visually coherent per business type.
// Every name, person, review and booking here is fake and demo-only. Media is chosen by the adapter from the
// manifest (category / subcategory), never assigned image-by-image.

// category slug → manifest subcategories used for that business type
export const MEDIA = {
  barber: { interior: ['barbers'], staff: ['barber'], results: ['mens-hair', 'beard'] },
  'hair-salon': {
    interior: ['hair-salons'],
    staff: ['hairstylist'],
    results: ['womens-haircut-styling', 'hair-color', 'balayage', 'blowout-styling'],
  },
  nails: {
    interior: ['nails'],
    staff: ['nail-technician'],
    results: ['manicure', 'nail-art', 'pedicure'],
  },
  'lashes-brows': {
    interior: ['brows-lashes'],
    staff: ['brow-lash-technician'],
    results: ['brows', 'lashes'],
  },
  spa: { interior: ['spas'], staff: ['spa-beauty-staff'], results: [] }, // the library has no spa results
  'beauty-center': { interior: ['beauty-salons'], staff: ['spa-beauty-staff'], results: [] },
};

const S = (canonical, name, price, minutes, extra = {}) => ({
  canonical,
  name,
  price,
  minutes,
  ...extra,
});

export const BUSINESSES = [
  {
    key: 'gentlemens-room',
    name: 'The Gentlemen’s Room',
    category: 'barber',
    area: 'hamra',
    audience: 'men',
    mode: 'instant',
    cancelMinutes: 180,
    description:
      'A classic Hamra barbershop: sharp fades, hot-towel shaves and beard work by a small, experienced team. Walk-ins welcome when a chair is free; booking guarantees your time.',
    staff: [
      ['Karim Haddad', 'Senior Barber', ['Fades', 'Beard design']],
      ['Ali Saad', 'Barber', ['Classic cuts']],
      ['Rami Khoury', 'Barber', ['Modern styles']],
    ],
    services: [
      S('mens-haircut', 'Men’s Cut', 18, 30),
      S('beard-trim', 'Beard Trim', 10, 20),
      S('haircut-beard', 'Cut + Beard', 25, 45),
      S('hot-towel-shave', 'Hot Towel Shave', 15, 30),
      S('kids-haircut', 'Kids Haircut', 12, 30),
    ],
    reviews: { count: 24, quality: 0.95, results: 6, texts: true },
    gallery: 4,
  },
  {
    key: 'fade-district',
    name: 'Fade District',
    category: 'barber',
    area: 'mar-mikhael',
    audience: 'men',
    mode: 'request',
    cancelMinutes: 1440,
    description: 'Skin fades and textured crops in Mar Mikhael.',
    staff: [
      ['Omar Nassar', 'Barber', ['Skin fades']],
      ['Jad Fares', 'Barber', []],
    ],
    services: [
      S('mens-haircut', 'Skin Fade', 15, 45),
      S('beard-trim', 'Beard Line-up', 8, 15),
      S('haircut-beard', 'Fade + Beard', 20, 60),
    ],
    reviews: { count: 9, quality: 0.7, results: 3, texts: true },
    gallery: 3,
  },
  {
    key: 'maison-de-beaute',
    name: 'Maison de Beauté',
    category: 'hair-salon',
    area: 'achrafieh',
    audience: 'women',
    mode: 'instant',
    cancelMinutes: 1440,
    description:
      'Colour specialists in Achrafieh. Balayage, glossing and precision cuts in a calm, light-filled salon. Consultations are free and every colour service starts with a strand test.',
    staff: [
      ['Maya Aoun', 'Colour Specialist', ['Balayage', 'Blonding']],
      ['Rima Salameh', 'Senior Stylist', ['Precision cuts']],
      ['Nour Hajj', 'Stylist', ['Blow-dry', 'Updos']],
      ['Lea Karam', 'Junior Stylist', []],
    ],
    services: [
      S('womens-haircut', 'Women’s Cut & Style', 35, 60),
      S('blow-dry', 'Blow-dry', 22, 45),
      S('hair-color', 'Root Colour', 55, 90, { type: 'from' }),
      S('balayage', 'Balayage', 120, 180, { type: 'range', max: 180 }),
      S('keratin', 'Keratin Treatment', null, 150, { type: 'on_consultation', online: false }),
    ],
    reviews: { count: 31, quality: 0.9, results: 8, texts: true },
    gallery: 4,
  },
  {
    key: 'salon-rita',
    name: 'Salon Rita',
    category: 'hair-salon',
    area: 'hazmieh',
    audience: 'everyone',
    mode: 'instant',
    cancelMinutes: 120,
    description: null,
    staff: [
      ['Rita Mansour', 'Owner & Stylist', []],
      ['Tala Issa', 'Stylist', []],
    ],
    services: [
      S('womens-haircut', 'Haircut', 20, 45),
      S('blow-dry', 'Blow-dry', 15, 30),
      S('hair-treatment', 'Hair Mask Treatment', 25, 45),
    ],
    reviews: { count: 0, quality: 0.8, results: 0 }, // new: no reviews yet
    gallery: 2,
  },
  {
    key: 'luma-studio',
    name: 'Luma Studio',
    category: 'nails',
    area: 'achrafieh',
    audience: 'women',
    mode: 'instant',
    cancelMinutes: 240,
    description: 'Gel, nail art and spa pedicures with sterilised tools and a curated colour bar.',
    staff: [
      ['Yara Chami', 'Nail Artist', ['Nail art']],
      ['Hiba Daher', 'Nail Technician', ['Gel']],
      ['Sara Rizk', 'Nail Technician', []],
    ],
    services: [
      S('manicure', 'Classic Manicure', 15, 30),
      S('gel-manicure', 'Gel Manicure', 25, 45),
      S('pedicure', 'Spa Pedicure', 28, 50),
      S('nail-art', 'Nail Art (per set)', 10, 30, { type: 'from' }),
    ],
    reviews: { count: 18, quality: 0.85, results: 6, texts: true },
    gallery: 3,
  },
  {
    key: 'polish-co',
    name: 'Polish & Co',
    category: 'nails',
    area: 'verdun',
    audience: 'women',
    mode: 'request',
    cancelMinutes: 1440,
    description: 'Neighbourhood nail bar in Verdun.',
    staff: [
      ['Dana Aziz', 'Nail Technician', []],
      ['Mira Khalil', 'Nail Technician', []],
    ],
    services: [
      S('manicure', 'Manicure', 12, 30),
      S('pedicure', 'Pedicure', 20, 45),
      S('nail-extensions', 'Nail Extensions', 40, 90),
    ],
    reviews: { count: 6, quality: 0.6, results: 2, texts: false },
    gallery: 2,
  },
  {
    key: 'brow-bar-beirut',
    name: 'Brow Bar Beirut',
    category: 'lashes-brows',
    area: 'hamra',
    audience: 'women',
    mode: 'instant',
    cancelMinutes: 240,
    description: 'Brow shaping, lamination and lash lifts — natural results, quick appointments.',
    staff: [
      ['Joelle Abi Nader', 'Brow Specialist', ['Lamination']],
      ['Christelle Maalouf', 'Lash Technician', ['Lash lift']],
    ],
    services: [
      S('brow-shaping', 'Brow Shaping', 12, 20),
      S('brow-lamination', 'Brow Lamination', 35, 45),
      S('lash-lift', 'Lash Lift & Tint', 40, 60),
      S('brow-tint', 'Brow Tint', 10, 15),
    ],
    reviews: { count: 14, quality: 0.88, results: 5, texts: true },
    gallery: 3,
  },
  {
    key: 'lash-atelier',
    name: 'Lash Atelier',
    category: 'lashes-brows',
    area: 'baabda-town',
    audience: 'women',
    mode: 'request',
    cancelMinutes: 1440,
    description: null,
    staff: [['Carla Haddad', 'Lash Artist', ['Volume lashes']]],
    services: [
      S('lash-extensions', 'Classic Lash Extensions', 60, 120),
      S('lash-lift', 'Lash Lift', 35, 60),
    ],
    reviews: { count: 3, quality: 0.75, results: 2, texts: false },
    gallery: 2,
  },
  {
    key: 'serene-spa',
    name: 'Serene Spa',
    category: 'spa',
    area: 'verdun',
    audience: 'everyone',
    mode: 'instant',
    cancelMinutes: 1440,
    description:
      'A quiet day spa in Verdun: deep-tissue and relaxing massages, facials and a traditional hammam. Couples rooms available on request.',
    staff: [
      ['Nadine Farah', 'Massage Therapist', ['Deep tissue']],
      ['Georges Bitar', 'Massage Therapist', []],
      ['Lara Sfeir', 'Aesthetician', ['Facials']],
    ],
    services: [
      S('massage', 'Relaxing Massage (60 min)', 45, 60),
      S('massage', 'Deep Tissue Massage', 55, 60),
      S('facial', 'Signature Facial', 50, 60),
      S('moroccan-bath', 'Moroccan Hammam', 40, 75),
    ],
    reviews: { count: 20, quality: 0.92, results: 0, texts: true },
    gallery: 4,
  },
  {
    key: 'beauty-corner',
    name: 'Beauty Corner',
    category: 'beauty-center',
    area: 'achrafieh',
    audience: 'women',
    mode: 'instant',
    cancelMinutes: 120,
    description: 'Waxing and threading, quick and friendly.',
    staff: [
      ['Samar Ghanem', 'Beautician', []],
      ['Rola Ayoub', 'Beautician', []],
    ],
    services: [
      S('waxing', 'Full Leg Wax', 20, 45),
      S('face-threading', 'Face Threading', 8, 15),
      S('waxing', 'Underarm Wax', 8, 15),
    ],
    reviews: { count: 11, quality: 0.72, results: 0, texts: false },
    gallery: 2,
  },
  {
    // contact-only example: services on consultation, not bookable online → "Ask about availability"
    key: 'glow-clinic',
    name: 'Glow Beauty Clinic',
    category: 'beauty-center',
    area: 'hazmieh',
    audience: 'everyone',
    mode: 'instant',
    cancelMinutes: 1440,
    description: 'Consultation-first beauty treatments. Message us to plan your visit.',
    staff: [['Dr. Rana Tabet', 'Consultant', []]],
    services: [
      S('waxing', 'Laser Consultation', null, 30, { type: 'on_consultation', online: false }),
      S('face-threading', 'Brow Design Consultation', null, 30, {
        type: 'on_consultation',
        online: false,
      }),
    ],
    reviews: { count: 2, quality: 0.8, results: 0, texts: false },
    gallery: 2,
  },
];

export const REVIEW_TEXTS = [
  'Best in the area. Professional, clean and always consistent.',
  'Booked the same day, no waiting. Exactly the result I asked for.',
  'Great atmosphere and attention to detail. Highly recommended.',
  'Friendly team and fair prices. I’ll be back.',
  'Took their time to understand what I wanted. Lovely experience.',
  'On time, spotless, and the result lasted weeks.',
];
export const FIRST_NAMES = [
  'Rami',
  'Jean',
  'Sarah',
  'Nadia',
  'Tony',
  'Maria',
  'Hadi',
  'Layal',
  'Fadi',
  'Rola',
  'Ziad',
  'Mona',
  'Elie',
  'Hala',
  'Samir',
  'Reem',
];
export const LAST_NAMES = [
  'Haddad',
  'Khoury',
  'Saleh',
  'Nasr',
  'Chahine',
  'Mrad',
  'Azar',
  'Fakhoury',
  'Karam',
  'Abboud',
];
