-- M9 · Review message templates (EN + AR) — generated by scripts/notification-templates.py.
-- Same rules as the M7 templates (Meta approval before WhatsApp sends; English fallback; SMS backup
-- only for critical types — these are not critical).

insert into public.notification_templates
  (type, channel, locale, provider_template_name, body, variables, buttons, button_labels, status, is_active)
values
  ('review_request', 'whatsapp', 'en', 'review_request_v1', 'How was your {service_name} at {business_name}? Leave a quick review, it helps others choose.', '{"service_name","business_name"}', '{"review"}', '{"Leave a review"}', 'draft', true),
  ('review_request', 'sms', 'en', null, 'How was your {service_name} at {business_name}? Leave a quick review, it helps others choose. Review: {review_link}', '{"service_name","business_name","review_link"}', '{}', '{}', 'approved', true),
  ('review_request', 'whatsapp', 'ar', 'review_request_v1', 'كيف كانت تجربتك مع {service_name} في {business_name}؟ اترك تقييمًا سريعًا، فهو يساعد الآخرين على الاختيار.', '{"service_name","business_name"}', '{"review"}', '{"اترك تقييمًا"}', 'draft', true),
  ('review_request', 'sms', 'ar', null, 'كيف كانت تجربتك مع {service_name} في {business_name}؟ اترك تقييمًا سريعًا، فهو يساعد الآخرين على الاختيار. للتقييم: {review_link}', '{"service_name","business_name","review_link"}', '{}', '{}', 'approved', true),
  ('review_needs_changes', 'whatsapp', 'en', 'review_needs_changes_v1', 'Your rating for {business_name} is live, but your comment couldn''t be published as written. You can edit it within 7 days.', '{"business_name"}', '{"review_edit"}', '{"Edit my review"}', 'draft', true),
  ('review_needs_changes', 'sms', 'en', null, 'Your rating for {business_name} is live, but your comment couldn''t be published as written. You can edit it within 7 days. Edit: {review_link}', '{"business_name","review_link"}', '{}', '{}', 'approved', true),
  ('review_needs_changes', 'whatsapp', 'ar', 'review_needs_changes_v1', 'تقييمك لـ {business_name} منشور، لكن تعليقك لم يُنشر بصيغته الحالية. يمكنك تعديله خلال 7 أيام.', '{"business_name"}', '{"review_edit"}', '{"تعديل تقييمي"}', 'draft', true),
  ('review_needs_changes', 'sms', 'ar', null, 'تقييمك لـ {business_name} منشور، لكن تعليقك لم يُنشر بصيغته الحالية. يمكنك تعديله خلال 7 أيام. للتعديل: {review_link}', '{"business_name","review_link"}', '{}', '{}', 'approved', true),
  ('biz_new_review', 'whatsapp', 'en', 'biz_new_review_v1', '⭐ New review for {service_name} with {staff_name}. Reply from your dashboard.', '{"service_name","staff_name"}', '{"reviews"}', '{"Open reviews"}', 'draft', true),
  ('biz_new_review', 'whatsapp', 'ar', 'biz_new_review_v1', '⭐ تقييم جديد لـ {service_name} مع {staff_name}. يمكنك الرد من لوحة التحكم.', '{"service_name","staff_name"}', '{"reviews"}', '{"فتح التقييمات"}', 'draft', true);
