-- M10 · Result photo messages (EN + AR) — generated by scripts/notification-templates.py.
-- WhatsApp only (non-critical). Same Meta approval rules as the M7 templates.

insert into private.notification_routes (type, primary_channels, fallback_channels, critical) values
  ('result_published', '{whatsapp}', '{}', false),
  ('result_rejected', '{whatsapp}', '{}', false)
on conflict (type) do nothing;

insert into public.notification_templates
  (type, channel, locale, provider_template_name, body, variables, buttons, button_labels, status, is_active)
values
  ('result_published', 'whatsapp', 'en', 'result_published_v1', '📸 Your photo from {business_name} is now live on their page. Thanks for sharing your result!', '{"business_name"}', '{"result"}', '{"View photo"}', 'draft', true),
  ('result_published', 'whatsapp', 'ar', 'result_published_v1', '📸 صورتك من {business_name} صارت منشورة على صفحتهم. شكرًا لمشاركتك النتيجة!', '{"business_name"}', '{"result"}', '{"عرض الصورة"}', 'draft', true),
  ('result_rejected', 'whatsapp', 'en', 'result_rejected_v1', 'One of your photos from {business_name} couldn''t be published: {photo_reason} You can add another photo within 30 days of your visit.', '{"business_name","photo_reason"}', '{"photos"}', '{"Add another photo"}', 'draft', true),
  ('result_rejected', 'whatsapp', 'ar', 'result_rejected_v1', 'لم نتمكن من نشر إحدى صورك من {business_name}: {photo_reason} يمكنك إضافة صورة أخرى خلال 30 يومًا من زيارتك.', '{"business_name","photo_reason"}', '{"photos"}', '{"أضف صورة أخرى"}', 'draft', true);
