-- M11 · Dispute messages (EN + AR) — generated by scripts/notification-templates.py.
-- WhatsApp only (non-critical); the booking page shows the outcome too. Same Meta approval rules as M7.

insert into private.notification_routes (type, primary_channels, fallback_channels, critical) values
  ('dispute_update', '{whatsapp}', '{}', false),
  ('biz_report_resolved', '{whatsapp}', '{}', false)
on conflict (type) do nothing;

insert into public.notification_templates
  (type, channel, locale, provider_template_name, body, variables, buttons, button_labels, status, is_active)
values
  ('dispute_update', 'whatsapp', 'en', 'dispute_update_v1', 'Update on your {service_name} booking at {business_name} on {date}: {dispute_result} Details are on your booking page.', '{"service_name","business_name","date","dispute_result"}', '{"view"}', '{"View booking"}', 'draft', true),
  ('dispute_update', 'whatsapp', 'ar', 'dispute_update_v1', 'تحديث بخصوص حجز {service_name} في {business_name} يوم {date}: {dispute_result} التفاصيل في صفحة حجزك.', '{"service_name","business_name","date","dispute_result"}', '{"view"}', '{"عرض الحجز"}', 'draft', true),
  ('biz_report_resolved', 'whatsapp', 'en', 'biz_report_resolved_v1', 'Update on the {service_name} booking with {customer_name} on {date}: {dispute_result} Details are in your dashboard.', '{"service_name","customer_name","date","dispute_result"}', '{"dashboard"}', '{"Open bookings"}', 'draft', true),
  ('biz_report_resolved', 'whatsapp', 'ar', 'biz_report_resolved_v1', 'تحديث بخصوص حجز {service_name} مع {customer_name} يوم {date}: {dispute_result} التفاصيل في لوحة التحكم.', '{"service_name","customer_name","date","dispute_result"}', '{"dashboard"}', '{"فتح الحجوزات"}', 'draft', true);
